import "./globals.css";

import Container from "@lib/shared/components/custom/Container";
import ApiClientProvider from "@shared/api/ApiClientProvider";
import ThemeProvider from "@shared/style/ThemeProvider";
import WalletProvider from "@shared/wallet/WalletProvider";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import Navbar from "@/lib/features/navigation/Navbar";

const spaceGroteskSans = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGroteskSans.variable} antialiased`}>
        <div className=" size-full min-h-screen overflow-x-hidden">
          <ThemeProvider>
            <WalletProvider>
              <ApiClientProvider>
                <Navbar />
                <Container>{children}</Container>
              </ApiClientProvider>
            </WalletProvider>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
